import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/layouts/header/header";
import { Poppins } from "next/font/google";
import { Footer } from "@/components/layouts/footer/footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "TouringCars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Header/> 
        {children}
        <Footer/>
      </body>
    </html>
  );
}
